# matriks
matriks merupakan bilangan yang terdiri dari baris dan kolom yaitu berupa bilangan real atau kompleks sehingga membentuk bilangan persegi atau persegi panjang.

Baris: Susunan bilangan-bilangan yang mendatar (horizontal).


Kolom: Susunan bilangan-bilangan yang tegak (vertikal).


Elemen: Bilangan-bilangan yang menyusun matriks.


Ordo: Pasangan bilangan yang menyatakan jumlah baris dan kolom matriks. Contohnya, matriks 2x3 memiliki ordo 2x3 karena memiliki 2 baris dan 3 kolom.

menggunakan pustaka numpy untuk bekerja dengan matriks agar menampilkan matriks dengan format yang lebih rapi.

In [1]:
import numpy as np
A =np.array([[1,3,5],[2,4,5],[3,5,6]])
B =np.array([[7,9,5],[3,8,5],[1,9,6]])
C =np.array([[1,4,6],[4,5,1]])
D =np.array([[3,4,6],[7,3,1],[1,4,9]])

print(A,"\n")
print(B,"\n")
print(C,"\n")
print(D,"\n")


[[1 3 5]
 [2 4 5]
 [3 5 6]] 

[[7 9 5]
 [3 8 5]
 [1 9 6]] 

[[1 4 6]
 [4 5 1]] 

[[3 4 6]
 [7 3 1]
 [1 4 9]] 



## Operasi Matriks
Ada beberapa operasi yang dapat dilakukan pada matriks, di antaranya:

-Penjumlahan dan pengurangan: Operasi ini hanya dapat dilakukan pada matriks yang memiliki ordo yang sama.


-Perkalian matriks: Operasi ini hanya dapat dilakukan pada matriks yang memiliki dimensi yang kompatibel.


-Transpos: Operasi ini menukar baris dan kolom matriks.


-Invers: Matriks yang mengalikan matriks lain menghasilkan matriks identitas.

In [2]:
# untuk membuat matriks secara random anda bisa menggunakan fungsi
# np.random.randit
E = np.random.randint(10,size=(3,3))
print(E)

[[8 0 5]
 [7 7 2]
 [0 3 3]]


## penjumlahan
adapun operasi penjumlahan pada matriks memiliki syarat yakni harus mempunyai ordo yang sama, jumlah baris dan kolom yang sama

adapun sifat-sifat penjumlahan matriks
 Sifat Komutatif

1. Sifat komutatif menyatakan bahwa urutan penjumlahan matriks tidak mengubah hasilnya.

dengan ketentuan A + B = B + A

2.  Sifat Asosiatif

Sifat asosiatif menyatakan bahwa cara pengelompokan penjumlahan matriks tidak mengubah hasilnya.

dengan ketentuan (A + B) + C = A + (B + C)

3. Sifat Elemen Netral

Sifat elemen netral menyatakan bahwa penjumlahan matriks dengan matriks nol menghasilkan matriks itu sendiri.

A + O = O + A = A

4.Sifat Elemen Invers

Sifat elemen invers menyatakan bahwa untuk setiap matriks A, terdapat matriks -A yang disebut elemen inversnya, sehingga penjumlahan keduanya menghasilkan matriks nol.

A + (-A) = O


In [3]:
# contoh penjumlahan matriks
M = A + B
print(A)
print(B)
print(M)

[[1 3 5]
 [2 4 5]
 [3 5 6]]
[[7 9 5]
 [3 8 5]
 [1 9 6]]
[[ 8 12 10]
 [ 5 12 10]
 [ 4 14 12]]


## pengurangan
untuk pengurangan pada matriks memiliki konsep yang sama seperti penjumlahan yakni harus memiliki ordo yang sama akan tetapi oprasi yang berjalan tetap pengurangan

contoh

In [4]:
# penguraangan
N = A - B
print(A)
print(B)
print(N)

[[1 3 5]
 [2 4 5]
 [3 5 6]]
[[7 9 5]
 [3 8 5]
 [1 9 6]]
[[-6 -6  0]
 [-1 -4  0]
 [ 2 -4  0]]


## perkalian matriks

Perkalian matriks adalah operasi matematika yang menggabungkan dua matriks menjadi satu matriks baru. berbeda dari penjumlahan dan pengurangan Perkalian matriks hanya dapat dilakukan pada dua matriks yang memiliki dimensi yang kompatibel.

Sifat-sifat Perkalian Matriks

Perkalian matriks memiliki beberapa sifat, di antaranya:

Sifat Asosiatif:
(A * B) * C = A * (B * C)

Sifat Distributif terhadap Penjumlahan:
A * (B + C) = A * B + A * C

Sifat Distributif terhadap Perkalian Skalar:
k * (A * B) = (k * A) * B = A * (k * B)

Sifat Elemen Netral:
A * I = I * A = A

In [5]:
#contoh perkalian dengan sifat distributif terhadap penjumlahan
c=2
d=4
G = (c+d)*A
H = (c*A)+(d*A)
print(G,"\n",H)

[[ 6 18 30]
 [12 24 30]
 [18 30 36]] 
 [[ 6 18 30]
 [12 24 30]
 [18 30 36]]


In [6]:
I = C.shape[3:2]
print(I)

()


## Transpos Matriks
Matriks transpos adalah matriks baru yang diperoleh dengan menukar baris menjadi kolom dan sebaliknya.

In [7]:
Q = A.transpose()
print(A)
print(Q)

[[1 3 5]
 [2 4 5]
 [3 5 6]]
[[1 2 3]
 [3 4 5]
 [5 5 6]]


In [8]:
A_T = A.transpose()
B_T = B.transpose()
C_T = C.transpose()
D_T = D.transpose()
K= A*A_T
L= A-A_T
print(A,"\n",A_T,"\n",K)
print(B_T)
print(C_T)
print(D_T)

[[1 3 5]
 [2 4 5]
 [3 5 6]] 
 [[1 2 3]
 [3 4 5]
 [5 5 6]] 
 [[ 1  6 15]
 [ 6 16 25]
 [15 25 36]]
[[7 3 1]
 [9 8 9]
 [5 5 6]]
[[1 4]
 [4 5]
 [6 1]]
[[3 7 1]
 [4 3 4]
 [6 1 9]]


In [9]:
O =(A+B)*D
R = O.transpose()
print(O)


[[ 24  48  60]
 [ 35  36  10]
 [  4  56 108]]
