# Matriks Invers
Matriks invers adalah matriks yang mengalikan matriks lain menghasilkan matriks identitas. Matriks identitas adalah matriks bujur sangkar dengan elemen diagonal utama sama dengan 1 dan elemen lainnya sama dengan 0.
Notasi:

Matriks invers dari matriks A dinotasikan dengan A^-1.

Syarat Memiliki Invers:

Tidak semua matriks memiliki invers. Suatu matriks A memiliki invers jika dan hanya jika determinannya (det(A)) tidak sama dengan 0.

#metode untuk mencari invers matriks, di antaranya:

## Metode Gauss-Jordan: Metode ini melibatkan operasi baris pada matriks A dan matriks identitas untuk menghasilkan matriks invers A^-1.

1. diberikan sebuah matrix sistem persamaan linear tiga variabel

\begin{align*}
    1x_1 + 2x_2 - 2x_3 &= -3\\
    1x_1 + 1x_2 + 1x_3 &= 5\\
    0x_1 + 0x_2  + 1x_3 &= 3
\end{align*}
2. ubah menjadi matrix $Ab$

\begin{bmatrix}
1 & 2 & -1\\
1 & 1 & -1\\
0 & 0 & 1
\end{bmatrix}

\begin{bmatrix}
-3\\
5\\
3
\end{bmatrix}

2. Bentuklah matriks yang diperbesar dengan matriks identitas $AI$.

\begin{bmatrix}
1 & 2 & -1 & 1 & 0 & 0\\
1 & 1 & -1 & 0 & 1 & 0\\
0 & 0 & 1 & 0 & 0 & 1
\end{bmatrix}
3. Lakukan operasi reduksi baris pada matriks yang diperbesar ini untuk menghasilkan bentuk $ IA^{-1}$

In [ ]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
AI = np.array([[1,2,-2,1,0,0],[1,1,1,0,1,0],[0,0,1,0,0,1]])
print(AI,"\n")

AI1 = RowAdd(AI,0,1,-1)
print(AI1,"\n")

AI2 = RowScale(AI1,1,-1)
print(AI2,"\n")

AI3 = RowAdd(AI2,1,0,-2)
print(AI3,"\n")

AI4 = RowAdd(AI3,2,1,3)
print(AI4,"\n")

AI5 = RowAdd(AI4,2,0,-4)
print(AI5,"\n")

[[ 1  2 -2  1  0  0]
 [ 1  1  1  0  1  0]
 [ 0  0  1  0  0  1]] 

[[ 1.  2. -2.  1.  0.  0.]
 [ 0. -1.  3. -1.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  2. -2.  1.  0.  0.]
 [-0.  1. -3.  1. -1. -0.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  0.  4. -1.  2.  0.]
 [-0.  1. -3.  1. -1. -0.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  0.  4. -1.  2.  0.]
 [ 0.  1.  0.  1. -1.  3.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  0.  0. -1.  2. -4.]
 [ 0.  1.  0.  1. -1.  3.]
 [ 0.  0.  1.  0.  0.  1.]] 



4. dari operasi di atas di dapat $IA^{-1} $
\begin{bmatrix}
1 & 0 & 0 &-1 & 2 & -4\\
0 & 1 & 0 & 1 & -1 & 3\\
0 & 0 & 1 & 0 & 0 & 1
\end{bmatrix}

maka $ A^{-1} $

\begin{bmatrix}
-1 & 2 & -4\\
1 & -1 & 3\\
0 & 0 & 1
\end{bmatrix}

5. cek apakah $AA^{-1}=I$

In [ ]:
A = np.array([[1,2,-2],[1,1,1],[0,0,1]])
AI6 = np.array([[-1,2,-4],[1,-1,3],[0,0,1]])
A_I = np.dot(A,AI6)
print(A_I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
b = np.array([[-3],[5], [3]])
print(b)
x = np.dot(AI6,b)
print(x)

[[-3]
 [ 5]
 [ 3]]
[[1]
 [1]
 [3]]


1. diberikan sebuah matrix sistem persamaan linear 4 variabel

\begin{align*}
    1x_1 + 2x_2 + 2x_3 + 4x_4&= -3\\
    0x_1 + 1x_2 + 1x_3 + 3x_4&= 6\\
    0x_1 + 0x_2  + 1x_3 + 2x_4&= 7\\
    2x_1 + x_2 + 4x_3 + 1x_4 =6
\end{align*}

2. ubah menjadi matrix $Ab$

\begin{bmatrix}
1 & 2 & 2 & 4\\
0 & 1 & 1 &3\\
0 & 0 & 1 & 2\\
2 & 1 & 4 & 1
\end{bmatrix}

\begin{bmatrix}
-3\\
6\\
7\\
6
\end{bmatrix}

In [ ]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
import numpy as np
A = np.array([[1,2,2,4],[1,1,1,3],[0,0,1,2],[2,1,4,1]])
B = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

print(A)
print(B)

[[1 2 2 4]
 [1 1 1 3]
 [0 0 1 2]
 [2 1 4 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
C = np.array([[1,2,2,4,1,0,0,0],[0,1,1,3,0,1,0,0],[0,0,1,2,0,0,1,0],[2,1,4,1,0,0,0,1]])
print(C)

[[1 2 2 4 1 0 0 0]
 [0 1 1 3 0 1 0 0]
 [0 0 1 2 0 0 1 0]
 [2 1 4 1 0 0 0 1]]


In [ ]:
C1 = RowAdd(C,0,3,-2)
print(C1)

[[ 1.  2.  2.  4.  1.  0.  0.  0.]
 [ 0.  1.  1.  3.  0.  1.  0.  0.]
 [ 0.  0.  1.  2.  0.  0.  1.  0.]
 [ 0. -3.  0. -7. -2.  0.  0.  1.]]


In [ ]:
C2 = RowAdd(C1,1,0,-2)
print(C2)

[[ 1.  0.  0. -2.  1. -2.  0.  0.]
 [ 0.  1.  1.  3.  0.  1.  0.  0.]
 [ 0.  0.  1.  2.  0.  0.  1.  0.]
 [ 0. -3.  0. -7. -2.  0.  0.  1.]]


In [ ]:
C3 = RowAdd(C2,1,3,3)
print(C3)

[[ 1.  0.  0. -2.  1. -2.  0.  0.]
 [ 0.  1.  1.  3.  0.  1.  0.  0.]
 [ 0.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  3.  2. -2.  3.  0.  1.]]


In [ ]:
C4 = RowAdd(C3,2,1,-1)
print(C4)

[[ 1.  0.  0. -2.  1. -2.  0.  0.]
 [ 0.  1.  0.  1.  0.  1. -1.  0.]
 [ 0.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  3.  2. -2.  3.  0.  1.]]


In [ ]:
C5= RowAdd(C4,2,3,-3)
print(C5)

[[ 1.  0.  0. -2.  1. -2.  0.  0.]
 [ 0.  1.  0.  1.  0.  1. -1.  0.]
 [ 0.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  0. -4. -2.  3. -3.  1.]]


In [ ]:
C6 = RowScale(C5,3,-0.25)
print(C6)

[[ 1.    0.    0.   -2.    1.   -2.    0.    0.  ]
 [ 0.    1.    0.    1.    0.    1.   -1.    0.  ]
 [ 0.    0.    1.    2.    0.    0.    1.    0.  ]
 [-0.   -0.   -0.    1.    0.5  -0.75  0.75 -0.25]]


In [ ]:
C7= RowAdd(C6,3,0,2)
print(C7)

[[ 1.    0.    0.    0.    2.   -3.5   1.5  -0.5 ]
 [ 0.    1.    0.    1.    0.    1.   -1.    0.  ]
 [ 0.    0.    1.    2.    0.    0.    1.    0.  ]
 [-0.   -0.   -0.    1.    0.5  -0.75  0.75 -0.25]]


In [ ]:
C8= RowAdd(C7,3,1,-1)
print(C8)

[[ 1.    0.    0.    0.    2.   -3.5   1.5  -0.5 ]
 [ 0.    1.    0.    0.   -0.5   1.75 -1.75  0.25]
 [ 0.    0.    1.    2.    0.    0.    1.    0.  ]
 [-0.   -0.   -0.    1.    0.5  -0.75  0.75 -0.25]]


In [ ]:
C9= RowAdd(C8,3,2,-2)
print(C9)

[[ 1.    0.    0.    0.    2.   -3.5   1.5  -0.5 ]
 [ 0.    1.    0.    0.   -0.5   1.75 -1.75  0.25]
 [ 0.    0.    1.    0.   -1.    1.5  -0.5   0.5 ]
 [-0.   -0.   -0.    1.    0.5  -0.75  0.75 -0.25]]


maka $A^{-1}$

\begin{bmatrix}
2 & -3.5 & 1.5 & -0.5\\
-0.5 & 1.75 & -1.75 &0.25\\
-1 & 1.5 & -0.5 & 0.5\\
0.5 & -0.75 & 0.75 & -0.25
\end{bmatrix}

In [ ]:
C10=np.array([[2,-3.5,1.5,-0.5],[-0.5,1.75,-1.75,0.25],[-1,1.5,-0.5,0.5],[0.5,-0.75,0.75,-0.25]])
D = np.array([[-3],[6],[7],[6]])
x = np.dot(C10,D)
print(x)

[[-19.5 ]
 [  1.25]
 [ 11.5 ]
 [ -2.25]]
